# **Importing Libraries**

In [1]:
import tensorflow as tf
import numpy as np

# **Differant rank tensors**

In [11]:
# Rank-0 tensor is a simple scaler value.. for e.g 4 is a rank-0 tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Rank-1 tensor is like a vector.. for e.g a list..
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)

# Rank-2 tensor is like a matrix.. for e.g a 2d lists..
rank_2_tensor = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(rank_2_tensor)

# Rank-3 tensor is a 3D matrix.. 
rank_3_tensor = tf.constant([
    [[1,1],[1,1],[1,1]],
    [[2,2],[2,2],[2,2]],
    [[3,3],[3,3],[3,3]]
])
print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]]], shape=(3, 3, 2), dtype=int32)


# **Converting tensor to numpy arrays**

In [16]:
# We can eith use np.array() or tensor.numpy() to convert a tensor to a numpy array..
r0_numpy = np.array(rank_0_tensor)
print("Rank-0 tensor->numpy: ", r0_numpy)

r1_numpy = rank_1_tensor.numpy()
print("Rank-1 tensor->numpy: ", r1_numpy)

# Similarly we can convert tensors of other shapes to numpy arrays using these functions..

Rank-0 tensor->numpy:  4
Rank-1 tensor->numpy:  [1 2 3]


# **Maths on Tensors**

In [30]:
# t1 is a 2x2 tesnor of ones..
t1 = tf.constant(tf.ones([2,2]))
t2 = tf.constant([[1,2],[3,4]], dtype='float32')

print("Addition: ", tf.add(t1, t2))
print("Multiplication: ", tf.multiply(t1, t2))
print("Matmul: ", tf.linalg.matmul(t2, t1))

Addition:  tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
Multiplication:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matmul:  tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)


# **Other tensor operations**

In [60]:
x = tf.constant([
    [4.0, 5.0],
    [10.0, 1.0]
])

print("Rank is: ", tf.rank(x))

# finding largest value..
print("Largest value: ", tf.reduce_max(x))

# index of largest value..
print("Largest value index: ", tf.math.argmax(x))

# doftmax on tensor..
print("Softmax result: ", tf.math.softmax(x))

Rank is:  tf.Tensor(2, shape=(), dtype=int32)
Largest value:  tf.Tensor(10.0, shape=(), dtype=float32)
Largest value index:  tf.Tensor([1 0], shape=(2,), dtype=int64)
Softmax result:  tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


# **4th rank-tensor and properties**

In [68]:
# creating a 4th renk tensor of ones..
rank_4_tensor = tf.constant(tf.ones([3,2,4,5]))
print("Rank of tensor is: ", tf.rank(rank_4_tensor).numpy())

# checking dimentions..
print("Dimentions are: ", rank_4_tensor.ndim)

# checking element's data-type..
print("Elements data-type is: ", rank_4_tensor.dtype)

# tensor shape..
print("Tensor shape is: ", rank_4_tensor.shape)

# elements along axis-0
print("Elements along axis 0 of tensor are: ", rank_4_tensor.shape[0])

# elements along last
print("Elements along last axis of tensor are: ", rank_4_tensor.shape[-1])

# total number of elements in rank-4 tensor..
print("Total elements are: ", tf.size(rank_4_tensor).numpy())

Rank of tensor is:  4
Dimentions are:  4
Elements data-type is:  <dtype: 'float32'>
Tensor shape is:  (3, 2, 4, 5)
Elements along axis 0 of tensor are:  3
Elements along last axis of tensor are:  5
Total elements are:  120


# **Rank-4 tensor shape analysis**

### Tensor-shape: (A, B, C, D)
* A -> Batch-size
* B -> Width
* C -> Height
* D -> Features


# **Rank-1 Tensor and indexing**

In [75]:
sample = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

# complete tensor..
print("Complete tensor: ", sample[:].numpy())
# start to 4th index..
print("Start index-->4th index: ", sample[:4].numpy())
# 4th index till end..
print("4th index-->last index: ", sample[4:].numpy())
# 2nd till 7th index..
print("2th index-->7th index: ", sample[2:7].numpy())
# skip 1 element from alternates..
print("Skipping alternates: ", sample[::2].numpy())
# printing in reverse..
print("Reversed: ", sample[::-1].numpy())

Complete tensor:  [ 0  1  1  2  3  5  8 13 21 34]
Start index-->4th index:  [0 1 1 2]
4th index-->last index:  [ 3  5  8 13 21 34]
2th index-->7th index:  [1 2 3 5 8]
Skipping alternates:  [ 0  1  3  8 21]
Reversed:  [34 21 13  8  5  3  2  1  1  0]


# **Rank-2 Tensor and indexing**

In [92]:
r2_tensor = rank_2_tensor
print("Rank-2 tensor is: ", r2_tensor)

# second row..
print("Second row: ", r2_tensor[1,:])
# second column..
print("Second column: ", r2_tensor[:,1])
# last row..
print("Last row: ", r2_tensor[-1,:])
# last column..
print("Last column: ", r2_tensor[:,-1])
# first item in last column..
print("First item in last column is: ", r2_tensor[0,-1])
# skipping 1st row..
print("Skipping 1st row: ")
print(r2_tensor[1:,:])

Rank-2 tensor is:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Second row:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Second column:  tf.Tensor([2 5 8], shape=(3,), dtype=int32)
Last row:  tf.Tensor([7 8 9], shape=(3,), dtype=int32)
Last column:  tf.Tensor([3 6 9], shape=(3,), dtype=int32)
First item in last column is:  tf.Tensor(3, shape=(), dtype=int32)
Skipping 1st row: 
tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)
