# **Importing Libraries**

In [2]:
import tensorflow as tf
import numpy as np

# **Differant rank tensors**

In [3]:
# Rank-0 tensor is a simple scaler value.. for e.g 4 is a rank-0 tensor
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

# Rank-1 tensor is like a vector.. for e.g a list..
rank_1_tensor = tf.constant([1,2,3])
print(rank_1_tensor)

# Rank-2 tensor is like a matrix.. for e.g a 2d lists..
rank_2_tensor = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(rank_2_tensor)

# Rank-3 tensor is a 3D matrix.. 
rank_3_tensor = tf.constant([
    [[1,1],[1,1],[1,1]],
    [[2,2],[2,2],[2,2]],
    [[3,3],[3,3],[3,3]]
])
print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]]], shape=(3, 3, 2), dtype=int32)


# **Converting tensor to numpy arrays**

In [4]:
# We can eith use np.array() or tensor.numpy() to convert a tensor to a numpy array..
r0_numpy = np.array(rank_0_tensor)
print("Rank-0 tensor->numpy: ", r0_numpy)

r1_numpy = rank_1_tensor.numpy()
print("Rank-1 tensor->numpy: ", r1_numpy)

# Similarly we can convert tensors of other shapes to numpy arrays using these functions..

Rank-0 tensor->numpy:  4
Rank-1 tensor->numpy:  [1 2 3]


# **Maths on Tensors**

In [5]:
# t1 is a 2x2 tesnor of ones..
t1 = tf.constant(tf.ones([2,2]))
t2 = tf.constant([[1,2],[3,4]], dtype='float32')

print("Addition: ", tf.add(t1, t2))
print("Multiplication: ", tf.multiply(t1, t2))
print("Matmul: ", tf.linalg.matmul(t2, t1))

Addition:  tf.Tensor(
[[2. 3.]
 [4. 5.]], shape=(2, 2), dtype=float32)
Multiplication:  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
Matmul:  tf.Tensor(
[[3. 3.]
 [7. 7.]], shape=(2, 2), dtype=float32)


# **Other tensor operations**

In [6]:
x = tf.constant([
    [4.0, 5.0],
    [10.0, 1.0]
])

print("Rank is: ", tf.rank(x))

# finding largest value..
print("Largest value: ", tf.reduce_max(x))

# index of largest value..
print("Largest value index: ", tf.math.argmax(x))

# doftmax on tensor..
print("Softmax result: ", tf.math.softmax(x))

Rank is:  tf.Tensor(2, shape=(), dtype=int32)
Largest value:  tf.Tensor(10.0, shape=(), dtype=float32)
Largest value index:  tf.Tensor([1 0], shape=(2,), dtype=int64)
Softmax result:  tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


# **4th rank-tensor and properties**

In [7]:
# creating a 4th renk tensor of ones..
rank_4_tensor = tf.constant(tf.ones([3,2,4,5]))
print("Rank of tensor is: ", tf.rank(rank_4_tensor).numpy())

# checking dimentions..
print("Dimentions are: ", rank_4_tensor.ndim)

# checking element's data-type..
print("Elements data-type is: ", rank_4_tensor.dtype)

# tensor shape..
print("Tensor shape is: ", rank_4_tensor.shape)

# elements along axis-0
print("Elements along axis 0 of tensor are: ", rank_4_tensor.shape[0])

# elements along last
print("Elements along last axis of tensor are: ", rank_4_tensor.shape[-1])

# total number of elements in rank-4 tensor..
print("Total elements are: ", tf.size(rank_4_tensor).numpy())

Rank of tensor is:  4
Dimentions are:  4
Elements data-type is:  <dtype: 'float32'>
Tensor shape is:  (3, 2, 4, 5)
Elements along axis 0 of tensor are:  3
Elements along last axis of tensor are:  5
Total elements are:  120


# **Rank-4 tensor shape analysis**

### Tensor-shape: (A, B, C, D)
* A -> Batch-size
* B -> Width
* C -> Height
* D -> Features


# **Rank-1 Tensor and indexing**

In [8]:
sample = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])

# complete tensor..
print("Complete tensor: ", sample[:].numpy())
# start to 4th index..
print("Start index-->4th index: ", sample[:4].numpy())
# 4th index till end..
print("4th index-->last index: ", sample[4:].numpy())
# 2nd till 7th index..
print("2th index-->7th index: ", sample[2:7].numpy())
# skip 1 element from alternates..
print("Skipping alternates: ", sample[::2].numpy())
# printing in reverse..
print("Reversed: ", sample[::-1].numpy())

Complete tensor:  [ 0  1  1  2  3  5  8 13 21 34]
Start index-->4th index:  [0 1 1 2]
4th index-->last index:  [ 3  5  8 13 21 34]
2th index-->7th index:  [1 2 3 5 8]
Skipping alternates:  [ 0  1  3  8 21]
Reversed:  [34 21 13  8  5  3  2  1  1  0]


# **Rank-2 Tensor and indexing**

In [9]:
r2_tensor = rank_2_tensor
print("Rank-2 tensor is: ", r2_tensor)

# second row..
print("Second row: ", r2_tensor[1,:])
# second column..
print("Second column: ", r2_tensor[:,1])
# last row..
print("Last row: ", r2_tensor[-1,:])
# last column..
print("Last column: ", r2_tensor[:,-1])
# first item in last column..
print("First item in last column is: ", r2_tensor[0,-1])
# skipping 1st row..
print("Skipping 1st row: ")
print(r2_tensor[1:,:])

Rank-2 tensor is:  tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
Second row:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)
Second column:  tf.Tensor([2 5 8], shape=(3,), dtype=int32)
Last row:  tf.Tensor([7 8 9], shape=(3,), dtype=int32)
Last column:  tf.Tensor([3 6 9], shape=(3,), dtype=int32)
First item in last column is:  tf.Tensor(3, shape=(), dtype=int32)
Skipping 1st row: 
tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)


# **Tensor shapes maupulation**

In [10]:
x = tf.constant([[1],[2],[3]])
print("Printing tensor x: ", x)
print("Printing shape of x: ", x.shape)
print("Printing shape as list: ", x.shape.as_list())

# reshaping tensor to (1,3)
reshaped_x = tf.reshape(x,(1,3))
print("Reshaped tensor is: ", reshaped_x)
print("Shape of reshaped tensor is: ", reshaped_x.shape)


Printing tensor x:  tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
Printing shape of x:  (3, 1)
Printing shape as list:  [3, 1]
Reshaped tensor is:  tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
Shape of reshaped tensor is:  (1, 3)


In [11]:
r3_tensor = rank_3_tensor
print("Original rank-3 tensor is: ", r3_tensor)
reshaped_r3 = tf.reshape(r3_tensor, (3,2,3))
print("Rank-3 tensor reshaped to (3,3,2): ", reshaped_r3)

# What-ever fits changes it into list for.. (1d tensor)
reshaped_r3 = tf.reshape(r3_tensor, [-1])
print("What-ever fits reshaping: ", reshaped_r3)   

# changes it into a (3, whatever shape fits)..
reshaped_r3 = tf.reshape(r3_tensor, [3,-1])
print("Reshaped 3d tensor becomes: ", reshaped_r3)

# changing rank-3 tensor to dims = (3,6)..
reshaped_r3 = tf.reshape(r3_tensor, [3,6])
print("Reshaped rank-3 tensor is: ", reshaped_r3)

Original rank-3 tensor is:  tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]]

 [[2 2]
  [2 2]
  [2 2]]

 [[3 3]
  [3 3]
  [3 3]]], shape=(3, 3, 2), dtype=int32)
Rank-3 tensor reshaped to (3,3,2):  tf.Tensor(
[[[1 1 1]
  [1 1 1]]

 [[2 2 2]
  [2 2 2]]

 [[3 3 3]
  [3 3 3]]], shape=(3, 2, 3), dtype=int32)
What-ever fits reshaping:  tf.Tensor([1 1 1 1 1 1 2 2 2 2 2 2 3 3 3 3 3 3], shape=(18,), dtype=int32)
Reshaped 3d tensor becomes:  tf.Tensor(
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]], shape=(3, 6), dtype=int32)
Reshaped rank-3 tensor is:  tf.Tensor(
[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [3 3 3 3 3 3]], shape=(3, 6), dtype=int32)


# **Note: You dont want to reshape the axis of a tensor**
# **Bad Practice**

In [12]:
print("Reshaping tensor axis: ", tf.reshape(rank_3_tensor, [2,3,3]))

Reshaping tensor axis:  tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [2 2 2]]

 [[2 2 2]
  [3 3 3]
  [3 3 3]]], shape=(2, 3, 3), dtype=int32)


# **Tensors type-casting**

In [13]:
# like other datatypes tensors can be typecasted..
f64_tensor = tf.constant([1,2,3], dtype=tf.float64)
print("Float64 tensor is: ", f64_tensor) 

# typecasting it to float32
f32_tensor = tf.cast(f64_tensor, dtype=tf.float32)
print("Type-casted float 32 tensor is: ", f32_tensor)

# typecasting to uint8
uint8_tensor = tf.cast(f64_tensor, dtype=tf.uint8)
print("Type-casted uint8 tensor is: ", uint8_tensor)

Float64 tensor is:  tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
Type-casted float 32 tensor is:  tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
Type-casted uint8 tensor is:  tf.Tensor([1 2 3], shape=(3,), dtype=uint8)


# **Tensor broadcasting**
* Smaller tensors are stretched to fit to a large tensor sometimes to perform arithimatic operations.
* Sometimes both the tensors are broadcasted to a new shape.

In [17]:
x = tf.constant([1,2,3])
y = tf.constant(2)
z = tf.constant([2,2,2])

# Multiplying tensor x by 2..
print("x*2 is: ", tf.multiply(x,2))

# Multiplying tensor x with y..
print("x*y is: ", x*y)

# Multiplying tensor x and z..
# corresponding elements are multiplied..
print("x*z is: ", x*z)

x*2 is:  tf.Tensor([2 4 6], shape=(3,), dtype=int32)
x*y is:  tf.Tensor([2 4 6], shape=(3,), dtype=int32)
x*z is:  tf.Tensor([2 4 6], shape=(3,), dtype=int32)


# **Broadcasting rank-1 tensor to rank-2 tensor**

In [18]:
x = tf.constant([1,2,3])

y = tf.broadcast_to(x,[3,3])

print("Broadcasted x tensor is: ", y)

Broadcasted x tensor is:  tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


# **tf.convert_to_tensor**
## **Compatible datatypes are automatically converted to tensors by calling the function like Numpy nd.arrays, lists etc..**

# **Ragged tensors**
# **Ir-regular shaped tensors are ragged tensors**
# **They cant be created with tf.constant function, instead they require tf.ragged.constant function for their declaration and initialization**

In [21]:
ragged_list = [
    [1],
    [1,2],
    [1,2,3],
    [1,2,3,4]
]

# Ragged tensors can't be decalred this way. It throws an error..
try:
    ragg_tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

# Right way of decalaring and initializing a ragged tensor..
ragg_tensor = tf.ragged.constant(ragged_list)
print("Ragged tensor is: ", ragg_tensor)

ValueError: Can't convert non-rectangular Python sequence to Tensor.
Ragged tensor is:  <tf.RaggedTensor [[1], [1, 2], [1, 2, 3], [1, 2, 3, 4]]>


# **String Tensors**

In [25]:
# You can also declare and initialize a string tensor..

string_tensor = tf.constant(["Quick brown fox","Jumped over a","Lazy dog"])
print("Printing string tensor: ", string_tensor)

# splitting a string tensor..
print(tf.strings.split(string_tensor))

Printing string tensor:  tf.Tensor([b'Quick brown fox' b'Jumped over a' b'Lazy dog'], shape=(3,), dtype=string)
<tf.RaggedTensor [[b'Quick', b'brown', b'fox'], [b'Jumped', b'over', b'a'],
 [b'Lazy', b'dog']]>


In [28]:
num_string = tf.constant(["1 10 100"])
print("Numbers string tensor is: ", num_string)

# converting it to a numbers tensor..
num_tensor = tf.strings.to_number(tf.strings.split(num_string, " "))
print("Converted number tensor is: ", num_tensor)

Numbers string tensor is:  tf.Tensor([b'1 10 100'], shape=(1,), dtype=string)
Converted number tensor is:  <tf.RaggedTensor [[1.0, 10.0, 100.0]]>
