# **Importing tensorflow and other libraries** 

In [1]:
import tensorflow as tf
import numpy as np

# **Tensorflow Variables**

In [13]:
# declaring tf constant..
x = tf.constant([[1,2],[3,4]])

# converting it to a tf variable..
y = tf.Variable(x)
print("Converted variable is: ", y)

# converting it to a numpy array..
nArray = y.numpy()
print("Tf variable --> numpy array is: ", nArray)

Converted variable is:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
Tf variable --> numpy array is:  [[1 2]
 [3 4]]


# **Checking properties**

In [14]:
print("Type is: ", y.dtype)
print("Shape is: ", y.shape)

Type is:  <dtype: 'int32'>
Shape is:  (2, 2)


# **Other variable functions**

In [16]:
# converting variable to tensor..
tens = tf.convert_to_tensor(y)
print("Printing tensor form: ", tens)

# getting heighest value index..
print("Heighest value index is: ", tf.argmax(y))

# reshaping variable to (1,4)
print("Reshaped varibale is: ", tf.reshape(y, [1,4]))

Printing tensor form:  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
Heighest value index is:  tf.Tensor([1 1], shape=(2,), dtype=int64)
Reshaped varibale is:  tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)


# **Re-assigning a variable**

In [21]:
# Note:
# tf.assign uses the memory of the same variable.
# to create a new variable use tf.Variable.assign

a = tf.Variable([2,3])
print("Variable is: ", a)

a.assign([1,2])
print("Reassigned variable is: ", a)

# variable reassignment requires the other varibale to be of the same size..

Variable is:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 3])>
Reassigned variable is:  <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


# **Operations and reassignment**

In [23]:
a = tf.Variable([1,2])
b = tf.Variable(a)

a.assign([5,6])
print("Numpy of variable a is: ", a.numpy())
print("Numpy of variable b is: ", b.numpy())

# adding and re-assigning 'a'
print("Adding and reassigning a: ", a.assign_add([1,2]))
print("Subtracting and reassigning a: ", a.assign_sub([6,8]))

Numpy of variable a is:  [5 6]
Numpy of variable b is:  [1 2]
Adding and reassigning a:  <tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([6, 8])>
Subtracting and reassigning a:  <tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([0, 0])>


# **Variables equality check**

In [28]:
print("Variable y: ", y)
v1 = tf.Variable(y, name = "V1")
yplus = tf.Variable(y+1, name = "V1")
print("y + 1: ", yplus)


# checking two variables are equal or not..
# despite the same name..
# both are unequal..
print("Variable equality: ", y==yplus)

Variable y:  <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>
y + 1:  <tf.Variable 'V1:0' shape=(2, 2) dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>
Variable equality:  tf.Tensor(
[[False False]
 [False False]], shape=(2, 2), dtype=bool)


# **Variable-Constant operations**

In [31]:
a = tf.constant([[1,2,3],[4,5,6]])
b = tf.Variable([[1,2],[3,4],[5,6]])
c = tf.constant([1,2,3])

# Matrix multiplication..
print("Matrix mul of a and b is: ", tf.matmul(a,b))

# in element-wise multiplication elements should have the same order..
print("Element-wise multiplication: ", a*c)

Matrix mul of a and b is:  tf.Tensor(
[[22 28]
 [49 64]], shape=(2, 2), dtype=int32)
Element-wise multiplication:  tf.Tensor(
[[ 1  4  9]
 [ 4 10 18]], shape=(2, 3), dtype=int32)
