# Defining a constant and checking properties..

In [1]:
import tensorflow as tf

x = tf.constant([[1., 2., 3.], [4., 5., 6.]])

print(x)
print(x.shape)
print(x.dtype)


tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
(2, 3)
<dtype: 'float32'>


# tf.constant operations..

In [2]:
# tensors addition..
print("Addition operation..")
print(x+x)

# tensor and scaler multiplication..
print("Multiplication operation..")
print(5*x)

# transpose calculates the transpose of the tensor..
print("Transpose operation..")
print(tf.transpose(x))

# concatination can be done based on axis
# axis zero refers to row based concatination and vice versa..
print("Concatination operation..")
print(tf.concat([x, x, x], axis=0))

# reduced sum calculates the sum of all the elements combined..
print("Reduced sum..")
print(tf.reduce_sum(x))

# exponential operation
# y = e**(element)
print("Exponential operation..")
print(tf.math.exp(x))

# softmax is computed using tf.exp(x) / tf.reduced_sum(tf.exp(x), axis)
print("Softmax..")
print(tf.nn.softmax(x))


Addition operation..
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float32)
Multiplication operation..
tf.Tensor(
[[ 5. 10. 15.]
 [20. 25. 30.]], shape=(2, 3), dtype=float32)
Transpose operation..
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
Concatination operation..
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]
 [1. 2. 3.]
 [4. 5. 6.]], shape=(6, 3), dtype=float32)
Reduced sum..
tf.Tensor(21.0, shape=(), dtype=float32)
Exponential operation..
tf.Tensor(
[[  2.7182817   7.389056   20.085537 ]
 [ 54.59815   148.41316   403.4288   ]], shape=(2, 3), dtype=float32)
Softmax..
tf.Tensor(
[[0.09003057 0.24472848 0.66524094]
 [0.09003057 0.24472848 0.66524094]], shape=(2, 3), dtype=float32)
